org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true

minecraft_version=1.20.1
forge_version=47.1.0
forge_version_range=[47.1.0,)
mapping_channel=official
mapping_version=1.20.1

mod_id=fixwaterwheel
mod_name=Fix Water Wheel
mod_version=1.0.0
mod_group=com.chasemeng.fixwaterwheel
mod_authors=ChaseMeng
mod_license=MIT