modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"
issueTrackerURL="https://github.com/ChaseMeng/FixWaterWheel/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''
Fix Water Wheel — 优化大量水车导致的客户端掉帧与服务端 tick 占用。
支持：固定光照、剔除扇叶旋转、完全剔除扇叶、服务端 tick 间隔调整。
'''

[[dependencies.${mod_id}]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.20.2)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
mandatory=true
versionRange="[0.5.1.j,)"
ordering="AFTER"
side="BOTH"